/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'

// Create Virtual Routes

const ProjectLazyImport = createFileRoute('/project')()
const HomeLazyImport = createFileRoute('/home')()
const ExperienceLazyImport = createFileRoute('/experience')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const ProjectLazyRoute = ProjectLazyImport.update({
  path: '/project',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~project.lazy').then((d) => d.Route))

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~home.lazy').then((d) => d.Route))

const ExperienceLazyRoute = ExperienceLazyImport.update({
  path: '/experience',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~experience.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~about.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceLazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AboutLazyRoute,
  ExperienceLazyRoute,
  HomeLazyRoute,
  ProjectLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/about",
        "/experience",
        "/home",
        "/project"
      ]
    },
    "/about": {
      "filePath": "~about.lazy.tsx"
    },
    "/experience": {
      "filePath": "~experience.lazy.tsx"
    },
    "/home": {
      "filePath": "~home.lazy.tsx"
    },
    "/project": {
      "filePath": "~project.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
